'use strict';

angular.module('aphrodite-docs')
.controller('CSSGenericController', function ($scope) {

    /*
     * Icons
     */
    $scope.icons = [
        'add',
        'arrow-left',
        'arrow-right',
        'arrow-up',
        'arrow-down',
        'android',
        'alert',
        'apple',
        'attach',
        'book',
        'bright',
        'cam',
        'card',
        'chat',
        'check',
        'check-list',
        'clock',
        'cloud',
        'directory',
        'download',
        'error',
        'esc',
        'facebook',
        'flag thick',
        'filter thick',
        'globe',
        'graph',
        'heart',
        'home',
        'info',
        'less',
        'link',
        'lock',
        'mail',
        'mic',
        'mobile',
        'move',
        'phone',
        'pic',
        'pause',
        'play',
        'print',
        'query',
        'qrcode',
        'qrframe',
        'smile',
        'reload',
        'search',
        'send',
        'settings',
        'suitcase',
        'target',
        'text',
        'ticket',
        'tickets',
        'trash',
        'twitter',
        'unlock',
        'upload',
        'user',
        'wallet',
        'watch',
        'song',
        'movie',
        'pencil',
        'filter',
        'bullet',
        'calendar',
        'brush',
    ];

});
